// backend/src/routes/fakeusers.js
const express = require('express');
const prisma = require('../utils/prisma');
const router = express.Router();

// единственный системный админ
const ADMIN_USER_ID = 1;

// Берём последние игровые статы для конкретного RealUser
async function getLatestStatsForRealUser(realUser) {
  if (!realUser || !realUser.password) return null;

  return prisma.gameProfile.findFirst({
    where: { playerId: realUser.password }, // 🔑 UUID из Ren'Py
    orderBy: { collected_at: 'desc' },
  });
}


// === helpers for dynamic bio from GameProfile ===
function formatPlaytime(seconds) {
  const totalMinutes = Math.floor((seconds || 0) / 60);
  if (totalMinutes <= 0) return 'меньше часа в системе';

  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;

  if (hours && minutes) return `${hours} ч ${minutes} мин в системе`;
  if (hours) return `${hours} ч в системе`;
  return `${minutes} мин в системе`;
}

function humanLang(code) {
  switch ((code || '').toLowerCase()) {
    case 'uk':
      return 'украинский';
    case 'ru':
      return 'русский';
    case 'en':
      return 'английский';
    case 'ja':
      return 'японский';
    case 'de':
      return 'немецкий';
    default:
      return `язык: ${code || 'неизвестный'}`;
  }
}

function generateDynamicBio(stats) {
  if (!stats) {
    return 'Autogenerated field operator.';
  }

  // === ВРЕМЯ ИГРЫ ===
  const play = formatPlaytime(stats.total_playtime || 0);

  // === ЯЗЫК СИСТЕМЫ ===
  const lang = humanLang(stats.system_lang);

  // === МЕСТОПОЛОЖЕНИЕ ===
  const country = stats.country || 'неустановленной страны';
  const city = stats.city ? `, ${stats.city}` : '';

  // === SAFE MODE ===
  const safe = stats.safe_mode
    ? 'SAFE-режим включён.'
    : 'SAFE-режим отключён.';

  // === ДРУГИЕ МЕТРИКИ ===
  const kassi = stats.kassi_named ? 'Kassi: установила контакт.' : 'Kassi: ещё не взаимодействовала.';
  const scarlett = stats.scarlett_taunts > 0
    ? `Scarlett взаимодействовала ${stats.scarlett_taunts} раз.`
    : 'Scarlett пока не проявляла активности.';
  const silvair = stats.silvair_rickroll > 0
    ? `Silvair Rickroll: ${stats.silvair_rickroll} раз.`
    : 'Silvair пока не вмешивался.';

  // === ФИНАЛЬНОЕ BIO ===
  return `
Стаж оператора: ${play}.
Локация: ${country}${city}.
Системный язык: ${lang}.
${safe}
  `.trim();
}

/* =======================================================
   📌 Получить ВСЕХ исследователей (с корректной подменой)
   ======================================================= */
router.get('/', async (req, res) => {
  try {
    const session = req.session?.user || null;

    const loggedUserId = session?.id || null;          // User.id
    const realUserId   = session?.realUser?.id || null; // RealUser.id
    const role         = session?.role || null;

    const fakeUsers = await prisma.fakeUser.findMany({
      orderBy: { id: 'asc' },
      include: { user: true },
    });

    // Админ — видит оригинальные FakeUser
    if (role === 'ADMIN') {
      return res.json(fakeUsers);
    }

    // Игрок — применяем подмену ТОЛЬКО для своего слота
    const result = await Promise.all(
      fakeUsers.map(async fu => {
        if (fu.userId !== loggedUserId) {
          return fu; // NPC и слот админа — без изменений
        }

        // загружаем realUser игрока
        const ru = await prisma.realUser.findUnique({
          where: { id: realUserId }
        });

        if (!ru) return fu;

        const latestStats = await getLatestStatsForRealUser(ru);
        console.log("🔥 STATS В FAKEUSERS:", latestStats?.total_playtime, latestStats);

        return {
          ...fu,
          codename: ru.username,
          avatarUrl: ru.avatarUrl || fu.avatarUrl,
          rank: 'Operator',
          clearance: 'D-13',
          bio: generateDynamicBio(latestStats)
        };
      })
    );

    return res.json(result);

  } catch (err) {
    console.error('FakeUsers list error:', err);
    return res.status(500).json({ error: 'Failed to load fake users' });
  }
});


/* =======================================================
   📌 Получить КОНКРЕТНОГО исследователя
   ======================================================= */
router.get('/:id', async (req, res) => {
  try {
    const id = Number(req.params.id);
    const session = req.session?.user || null;

    const loggedUserId = session?.id || null;         
    const realUserId   = session?.realUser?.id || null; 
    const role         = session?.role || null;

    let fu = await prisma.fakeUser.findUnique({
      where: { id },
      include: {
        user: true,
        posts: { orderBy: { createdAt: 'desc' } }
      },
    });

    if (!fu) return res.status(404).json({ error: 'Researcher not found' });

    // Админ: оригинал
    if (role === 'ADMIN') return res.json(fu);

    // Подмена для слота игрока
    if (fu.userId === loggedUserId) {
      const ru = await prisma.realUser.findUnique({
        where: { id: realUserId }
      });

      if (ru) {
        const latestStats = await getLatestStatsForRealUser(ru);
        console.log("🔥 STATS В FAKEUSERS:", latestStats?.total_playtime, latestStats);

        fu = {
          ...fu,
          codename: ru.username,
          avatarUrl: ru.avatarUrl || fu.avatarUrl,
          rank: 'Operator',
          clearance: 'D-13',
          bio: generateDynamicBio(latestStats)
        };
      }
    }

    return res.json(fu);

  } catch (err) {
    console.error('FakeUser profile error:', err);
    return res.status(500).json({ error: 'Failed to load researcher' });
  }
});


/* =======================================================
   📌 Посты пользователя (с подменой автора)
   ======================================================= */
router.get('/:id/posts', async (req, res) => {
  try {
    const id = Number(req.params.id);
    const session = req.session?.user || null;

    const loggedUserId = session?.id || null;
    const realUserId   = session?.realUser?.id || null;
    const role         = session?.role || null;

    const fu = await prisma.fakeUser.findUnique({
      where: { id },
      include: { user: true }
    });

    if (!fu) return res.status(404).json({ error: 'Researcher not found' });

    // Загружаем посты
    let posts = await prisma.post.findMany({
      where: { fakeAuthorId: fu.id },
      orderBy: { createdAt: 'desc' },
      include: { fakeAuthor: true }
    });

    // Админ видит всё как есть
    if (role === 'ADMIN') {
      return res.json({ posts });
    }

    // Игрок: подмена автора для собственного FakeUser
    if (fu.userId === loggedUserId) {
      const ru = await prisma.realUser.findUnique({
        where: { id: realUserId }
      });

      if (ru) {
        const latestStats = await getLatestStatsForRealUser(ru);
        console.log("🔥 STATS В FAKEUSER POSTS:", latestStats?.total_playtime, latestStats);

        posts = posts.map(p => ({
          ...p,
          fakeAuthor: {
            ...p.fakeAuthor,
            codename: ru.username,
            avatarUrl: ru.avatarUrl || p.fakeAuthor.avatarUrl,
            rank: 'Operator',
            clearance: 'D-13',
            bio: generateDynamicBio(latestStats)
          }
        }));
      }
    }

    return res.json({ posts });

  } catch (err) {
    console.error('FakeUser posts error:', err);
    return res.status(500).json({ error: 'Failed to load posts' });
  }
});

module.exports = router;
