const express = require('express');
const router = express.Router();
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

router.get('/', async (req, res) => {
  try {
    const adminEmail = 'admin@center.local';
    const userEmail = 'user@center.local';

    const adminPass = await bcrypt.hash('veslo22lapti!', 10);
    const userPass = await bcrypt.hash('RulerLovesYou', 10);

    const admin = await prisma.user.upsert({
      where: { email: adminEmail },
      update: {},
      create: {
        email: adminEmail,
        password: adminPass,
        role: 'ADMIN',
        name: 'System Administrator',
        title: 'Lead Investigator',
        bio: 'Access Level: Root. Clearance: Ω.',
        avatarUrl: null,
      },
    });

    const user = await prisma.user.upsert({
      where: { email: userEmail },
      update: {},
      create: {
        email: userEmail,
        password: userPass,
        role: 'USER',
        name: 'Field Operator',
        title: 'Section D-13',
        bio: 'Assigned to Substructure Survey Team.',
        avatarUrl: null,
      },
    });

    // FakeUsers
    await prisma.fakeUser.upsert({
      where: { userId: admin.id },
      update: {},
      create: {
        codename: 'SYS-ADMIN',
        rank: 'Lead Investigator',
        clearance: 'Ω',
        bio: 'System-level investigator (autogenerated).',
        avatarUrl: null,
        userId: admin.id,
      },
    });

    await prisma.fakeUser.upsert({
      where: { userId: user.id },
      update: {},
      create: {
        codename: 'FIELD-OP',
        rank: 'Operator',
        clearance: 'D-13',
        bio: 'Autogenerated field operator.',
        avatarUrl: null,
        userId: user.id,
      },
    });

    res.json({
      success: true,
      message: 'Seed complete: admin, user and FakeUsers created.',
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
