const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcrypt');

const prisma = new PrismaClient();

async function main() {
  const adminEmail = 'admin@center.local';
  const userEmail = 'user@center.local';

  const adminPass = await bcrypt.hash('admin123', 10);
  const userPass = await bcrypt.hash('user123', 10);

  // === 1) Создаём / обновляем ADMIN ===
  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      password: adminPass,
      role: 'ADMIN',
      name: 'System Administrator',
      title: 'Lead Investigator',
      bio: 'Access Level: Root. Clearance: Ω.',
      avatarUrl: null,
    },
  });

  // === 2) Создаём / обновляем обычного USER ===
  const user = await prisma.user.upsert({
    where: { email: userEmail },
    update: {},
    create: {
      email: userEmail,
      password: userPass,
      role: 'USER',
      name: 'Field Operator',
      title: 'Section D-13',
      bio: 'Assigned to Substructure Survey Team.',
      avatarUrl: null,
    },
  });

  // === 3) Создаём FakeUser для ADMIN ===
  await prisma.fakeUser.upsert({
    where: { userId: admin.id }, // уникальная связь
    update: {},
    create: {
      codename: 'SYS-ADMIN',
      rank: 'Lead Investigator',
      clearance: 'Ω',
      bio: 'System-level investigator (autogenerated).',
      avatarUrl: null,
      userId: admin.id,
    },
  });

  // === 4) Создаём FakeUser для обычного USER ===
  await prisma.fakeUser.upsert({
    where: { userId: user.id },
    update: {},
    create: {
      codename: 'FIELD-OP',
      rank: 'Operator',
      clearance: 'D-13',
      bio: 'Autogenerated field operator.',
      avatarUrl: null,
      userId: user.id,
    },
  });

  console.log('Seed complete: admin, user and linked FakeUsers created.');
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
