const prisma = require('../utils/prisma');
const { publicUrl } = require('../services/storage');

// === helpers for dynamic bio from GameProfile ===
function formatPlaytime(seconds) {
  const totalMinutes = Math.floor((seconds || 0) / 60);
  if (totalMinutes <= 0) return 'меньше часа в системе';

  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;

  if (hours && minutes) return `${hours} ч ${minutes} мин в системе`;
  if (hours) return `${hours} ч в системе`;
  return `${minutes} мин в системе`;
}

function humanLang(code) {
  switch ((code || '').toLowerCase()) {
    case 'uk':
      return 'украинский';
    case 'ru':
      return 'русский';
    case 'en':
      return 'английский';
    case 'ja':
      return 'японский';
    case 'de':
      return 'немецкий';
    default:
      return `язык: ${code || 'неизвестный'}`;
  }
}

function generateDynamicBio(stats) {
  if (!stats) {
    return 'Autogenerated field operator.';
  }

  // === ВРЕМЯ ИГРЫ ===
  const play = formatPlaytime(stats.total_playtime || 0);

  // === ЯЗЫК СИСТЕМЫ ===
  const lang = humanLang(stats.system_lang);

  // === МЕСТОПОЛОЖЕНИЕ ===
  const country = stats.country || 'неустановленной страны';
  const city = stats.city ? `, ${stats.city}` : '';

  // === SAFE MODE ===
  const safe = stats.safe_mode
    ? 'SAFE-режим включён.'
    : 'SAFE-режим отключён.';

  // === ДРУГИЕ МЕТРИКИ ===
  const kassi = stats.kassi_named ? 'Kassi: установила контакт.' : 'Kassi: ещё не взаимодействовала.';
  const scarlett = stats.scarlett_taunts > 0
    ? `Scarlett взаимодействовала ${stats.scarlett_taunts} раз.`
    : 'Scarlett пока не проявляла активности.';
  const silvair = stats.silvair_rickroll > 0
    ? `Silvair Rickroll: ${stats.silvair_rickroll} раз.`
    : 'Silvair пока не вмешивался.';

  // === ФИНАЛЬНОЕ BIO ===
  return `
Стаж оператора: ${play}.
Локация: ${country}${city}.
Системный язык: ${lang}.
${safe}
  `.trim();
}


/* === Получить список постов === */
async function listPosts(_req, res) {
  try {
    const posts = await prisma.post.findMany({
      orderBy: { createdAt: 'desc' },
      include: {
        images: true,
        fakeAuthor: true, // 👈 связь с FakeUser
      },
    });

    const withViews = await Promise.all(
      posts.map(async (p) => {
        const v = await prisma.view.count({ where: { postId: p.id } });
        return {
          ...p,
          viewsCount: v,
          author: p.fakeAuthor || null, // 👈 добавляем псевдоним
        };
      })
    );

    res.json(withViews);
  } catch (err) {
    console.error('Ошибка получения списка постов:', err);
    res.status(500).json({ error: 'Server error while listing posts' });
  }
}

async function getPost(req, res) {
  try {
    const id = Number(req.params.id);
    if (!id || isNaN(id)) {
      return res.status(400).json({ error: 'Invalid post ID' });
    }

    const session = req.session?.user || null;

    const loggedUserId = session?.id || null;          
    const realUserId   = session?.realUser?.id || null; 
    const role         = session?.role || null;

    // загружаем пост
    let post = await prisma.post.findUnique({
      where: { id },
      include: {
        images: true,
        fakeAuthor: true,
      },
    });

    if (!post) return res.status(404).json({ error: 'Post not found' });

    // считаем просмотры
    const viewsCount = await prisma.view.count({ where: { postId: id } });

    // === 🟥 Админ — без подмены ===
    if (role === 'ADMIN') {
      return res.json({
        ...post,
        author: post.fakeAuthor,
        viewsCount,
      });
    }

    // === 🟦 Собственный слот игрока — подмена автора ===
    if (post.fakeAuthor?.userId === loggedUserId) {

      // Загружаем RealUser
      const ru = await prisma.realUser.findUnique({
        where: { id: realUserId }
      });

      if (ru) {
        // ⬇️ Загружаем ПОСЛЕДНИЙ GameProfile ТОЛЬКО по playerId (UUID)
        const stats = await prisma.gameProfile.findFirst({
          where: { playerId: ru.password },
          orderBy: { collected_at: 'desc' }
        });

        console.log("🔥 ПОСЛЕДНИЙ STATS ДЛЯ ПОСТА:", stats?.total_playtime);

        const substitutedAuthor = {
          ...post.fakeAuthor,
          codename: ru.username,
          avatarUrl: ru.avatarUrl || post.fakeAuthor.avatarUrl,
          rank: 'Operator',
          clearance: 'D-13',

          // ⬇️ Передаём именно ПОСЛЕДНИЕ СТАТЫ
          bio: stats ? generateDynamicBio(stats) : "Autogenerated field operator."
        };

        return res.json({
          ...post,
          fakeAuthor: substitutedAuthor,
          author: substitutedAuthor,
          viewsCount,
        });
      }
    }

    // === обычный NPC / чужой слот ===
    return res.json({
      ...post,
      author: post.fakeAuthor,
      viewsCount,
    });

  } catch (err) {
    console.error('Ошибка получения поста:', err);
    res.status(500).json({ error: 'Server error while fetching post' });
  }
}


/* === Получить архив (посты с обложками) === */
async function listArchive(_req, res) {
  try {
    const posts = await prisma.post.findMany({
      where: { NOT: { coverImage: null } },
      orderBy: { createdAt: 'desc' },
      include: {
        fakeAuthor: true,
      },
    });

    res.json(
      posts.map((p) => ({
        ...p,
        author: p.fakeAuthor || null,
      }))
    );
  } catch (err) {
    console.error('Ошибка архива:', err);
    res.status(500).json({ error: 'Failed to fetch archive' });
  }
}

/* === Создать пост === */
async function createPost(req, res) {
  try {
    const {
      title,
      body,
      coverCaption,
      stamp,
      clearance,
      fakeAuthorId, // 👈 приходит с фронта
    } = req.body;

    if (!title || !body) {
      return res.status(400).json({ error: 'title and body are required' });
    }

    let coverImage = null;
    if (req.file) {
      coverImage = publicUrl(req.file.path);
    }

    let fileType = null;
      if (req.file) {
        fileType = req.file.mimetype || null; // например "image/png" или "application/pdf"
      }

    const created = await prisma.post.create({
      data: {
        title,
        body,
        coverImage,
        coverCaption: coverCaption || null,
        stamp: stamp || null,
        clearance: clearance || null,
        fakeAuthorId: fakeAuthorId ? Number(fakeAuthorId) : null, 
        fileType,// ✅ ключевое
      },
      include: { fakeAuthor: true },
    });

    // 👇 добавляем псевдоним author
    res.status(201).json({ ...created, author: created.fakeAuthor || null });
  } catch (err) {
    console.error('Ошибка при создании поста:', err);
    res.status(500).json({ error: 'Failed to create post' });
  }
}

/* === Обновить пост === */
async function updatePost(req, res) {
  try {
    const id = Number(req.params.id);
    const {
      title,
      body,
      coverCaption,
      stamp,
      clearance,
      fakeAuthorId,
    } = req.body;

    const exists = await prisma.post.findUnique({ where: { id } });
    if (!exists) return res.status(404).json({ error: 'Post not found' });

    let coverImage = exists.coverImage;
    if (req.files?.cover?.[0]) {
      coverImage = publicUrl(req.files.cover[0].path);
    }

    const updated = await prisma.post.update({
      where: { id },
      data: {
        title,
        body,
        coverImage,
        coverCaption: coverCaption || exists.coverCaption,
        stamp: stamp || exists.stamp,
        clearance: clearance || exists.clearance,
        fakeAuthorId: fakeAuthorId
          ? Number(fakeAuthorId)
          : exists.fakeAuthorId,
      },
      include: { fakeAuthor: true },
    });

    // Обновляем галерею, если есть новые файлы
    if (req.files && req.files.images) {
      const imgs = req.files.images.map((f) => ({
        postId: updated.id,
        imageUrl: publicUrl(f.path),
        caption: null,
      }));
      if (imgs.length) await prisma.postImage.createMany({ data: imgs });
    }

    res.json({ ...updated, author: updated.fakeAuthor || null });
  } catch (err) {
    console.error('Ошибка при обновлении поста:', err);
    res.status(500).json({ error: 'Failed to update post' });
  }
}

/* === Удалить пост === */
async function deletePost(req, res) {
  try {
    const id = Number(req.params.id);
    await prisma.post.delete({ where: { id } });
    res.json({ message: 'Deleted' });
  } catch (err) {
    console.error('Ошибка при удалении поста:', err);
    res.status(500).json({ error: 'Failed to delete post' });
  }
}

/* === Добавить просмотр поста === */
async function addView(req, res) {
  try {
    const id = Number(req.params.id);
    const { sessionId } = req.body;

    if (!id || !sessionId) {
      return res.status(400).json({ error: 'Missing post id or sessionId' });
    }

    await prisma.view.create({
      data: { postId: id, sessionId },
    });

    res.json({ message: 'View recorded' });
  } catch (err) {
    console.error('Error recording view:', err);
    res.status(500).json({ error: 'Failed to record view' });
  }
}

module.exports = {
  listPosts,
  getPost,
  listArchive,
  addView,
  createPost,
  updatePost,
  deletePost,
};
